baseURL = "https://samjudd.github.io/"
languageCode = "en-us"
title = "Sam Judd"
theme = "papermod"

[params]
author = "Sam Judd"
ShowToc = true

[params.homeInfoParams]
Title = "Sam's Blog"
Content = """
Hi, I am a manufacturing engineer at Blue Origin currently working on manufacturing engineering for  3D printed copper rocket components. 
I made this blog to document my efforts moonlighting as a solo game developer. 

__Contact Me:__ samjudd [at] protonmail [dot] com
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/samjudd"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/mala_mut3"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/juddsamuel/"